version: '3'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
      - POSTGRES_DB=employeedb
    ports:
      - '5432:5432'

  webapp:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - activemq

  activemq:
    image: rmohr/activemq
    ports:
      - '61616:61616'
      - '8161:8161'

